/* suitcases-data.js — スーツケース比較帳のデータ。仕様・価格は各社公式ページの確認値、評価は主観 */
var SUITCASES_META = {"checked": "2026-09-08"};
var SUITCASES = [
 {
  "id": "lojel-cubo-m",
  "brand": "LOJEL",
  "model": "Cubo (v5)",
  "variant": "M / 70L",
  "url": "https://item.rakuten.co.jp/lojel/cubo-medium/",
  "image": "https://shop.r10s.jp/lojel/cabinet/12729850/13215706/imgrc0134883725.jpg",
  "price": 63800,
  "currency": "JPY",
  "price_note": "税込・通常価格（LOJEL公式楽天ストア、全色同額）",
  "capacity": 70,
  "capacity_exp": 77,
  "weight": 4.3,
  "size": "65×45×30（拡張時 奥行33）",
  "open": "ブックオープン(片開き)",
  "stopper": false,
  "expandable": true,
  "wheels": "静音性強化型 双輪キャスター（LOJEL特注 TPE、非加水分解）",
  "warranty": "10年条件付",
  "colors": 7,
  "made_in": null,
  "notes": "フラットトップオープニング（片面横開き）。ボディはリサイクルPC50%配合、内装生地は取り外して洗える。三辺合計140cm。ストッパーはスペック表に記載なし（購入者レビューでも「ストッパーが付いていれば満点」と指摘）。ページタイトルは「全11色」だが購入選択肢は7色。生産国はページに記載なし。",
  "pick": 1,
  "rate": {
   "light": 3,
   "func": 4,
   "design": 5,
   "trust": 4,
   "value": 3
  },
  "comment": "旅行用品に見えない色と、狭い部屋で<b>立てたまま片側から開けられる</b>のが最大の利点。拡張つき・10年条件付保証。ストッパーがないのと、値上がりして高級品に寄ったのが難点。",
  "fit": "見た目で選びたい。ホテルの部屋が狭くても困りたくない"
 },
 {
  "id": "innovator-inv650dor",
  "brand": "innovator",
  "model": "Extreme Journey",
  "variant": "INV650DOR / 75L Middle",
  "url": "https://shop.innovator.co.jp/products/inv650dor-blueblack",
  "image": "https://cdn.shopify.com/s/files/1/0606/0477/6627/files/650_8079ee94-6654-4dd6-9249-6fd3ca45fe38.jpg?v=1748496278",
  "price": 29700,
  "currency": "JPY",
  "price_note": "税込・通常価格（innovator公式オンラインショップ、全14色同額。トコー公式Yahoo店・他正規店も同額）",
  "capacity": 75,
  "capacity_exp": null,
  "weight": 4.6,
  "size": "70.5×41×33",
  "open": "フロントオープン（横開きフロントドア＋メインジッパー）",
  "stopper": true,
  "expandable": false,
  "wheels": "消音双輪キャスター 60mm（HINOMOTO製 Lisof）",
  "warranty": "2年（製造上の不良に対する無償修理）",
  "colors": 14,
  "made_in": null,
  "notes": "三辺合計144.5cmで無料預入サイズ。ワンタッチのブレーキ（キャスターストッパー）搭載。55LのINV155（¥25,080）もあるが65–70Lに近い方としてINV650を選定。指示にあった innovator-japan.com はDNS解決不可（公式は innovator.co.jp / shop.innovator.co.jp）。生産国はページ記載なし。",
  "pick": 2,
  "rate": {
   "light": 3,
   "func": 5,
   "design": 4,
   "trust": 3,
   "value": 5
  },
  "comment": "北欧色14色、フロントオープン、ワンタッチのブレーキがこの価格で揃う。<b>コスパの基準点</b>。75Lはやや大きめなので、軽く持ちたいなら55LのINV155（¥25,080）。",
  "fit": "3万円前後で色と機能を両立したい"
 },
 {
  "id": "proteca-360s-metallic-d2-70",
  "brand": "PROTECA",
  "model": "360s メタリックD2",
  "variant": "70L / 01453",
  "url": "https://store.ace.jp/shop/g/g01453-13/",
  "image": "https://store.ace.jp/img/goods/L/01453-13.jpg",
  "price": 85800,
  "currency": "JPY",
  "price_note": "通常価格 税込85,800円。エース公式通販で現在SALE 30%OFF ¥60,060（税込）、さらに会員限定10%OFF表示。セール品は返品交換不可・プレミアムケア3年保証の対象外",
  "capacity": 70,
  "capacity_exp": null,
  "weight": 4.0,
  "size": "65×48×27",
  "open": "360オープン",
  "stopper": false,
  "expandable": false,
  "wheels": "サイレントキャスター（静音双輪）",
  "warranty": "プロテカ プレミアムケア 3年保証（セール品は対象外と明記）",
  "colors": 1,
  "made_in": "日本",
  "notes": "タテにもヨコにも開けられる360°オープンシステム、片面収納。北海道・赤平工場の日本製。公式ページに「キャスターストッパー非搭載モデル」と明記。70Lは現在ヘアラインシャンパン（13）1色のみ販売中（ネイビーは36Lのみ）。",
  "pick": 3,
  "rate": {
   "light": 4,
   "func": 4,
   "design": 3,
   "trust": 5,
   "value": 3
  },
  "comment": "北海道の工場で作る日本製、修理体制つきの「長く使う1個」。<b>縦にも横にも開く360°オープン</b>で狭い部屋に強く、70Lで4.0kg。今はシャンパン1色のみ・ストッパーなし。",
  "fit": "10年使う前提で、信頼性を最優先にしたい"
 },
 {
  "id": "ace-cresta2-60",
  "brand": "ACE",
  "model": "クレスタ2",
  "variant": "Mサイズ 60L / 06937",
  "url": "https://store.ace.jp/shop/g/g06937-01/",
  "image": "https://store.ace.jp/img/goods/L/06937-01.jpg",
  "price": 30800,
  "currency": "JPY",
  "price_note": "通常価格 税込30,800円。エース公式通販で 9/9 9:59まで TIME SALE 20%OFF ¥24,640（さらに会員限定10%OFF表示）。楽天エース公式店も30,800円",
  "capacity": 60,
  "capacity_exp": null,
  "weight": 3.8,
  "size": "67×44×27（本体 60×42×27）",
  "open": "ジッパー両開き",
  "stopper": true,
  "expandable": false,
  "wheels": "双輪キャスター（HINOMOTO製）",
  "warranty": null,
  "colors": 6,
  "made_in": "中国",
  "notes": "商品ページに保証期間の記載なし（エースの一般的な製品保証ページ参照が必要）。WEB限定モデル。キャスターストッパー、コの字ファスナー中仕切り、サイドハンドル・グライド付。ABS混合樹脂。三辺合計138cm。カラーはブラック／ブラウン（直営限定）／シルバー／ブロンズ／シャンパン／スカイブルーの各ヘアライン。",
  "pick": 4,
  "rate": {
   "light": 4,
   "func": 4,
   "design": 2,
   "trust": 4,
   "value": 5
  },
  "comment": "ACEの実直な量産機。<b>ストッパー付きで3.8kg</b>、通常3万円で今はセール中。見た目は無難だが、シャンパンやスカイブルーなど黒以外が選べる。",
  "fit": "予算を抑えて確実に使えるものがほしい"
 },
 {
  "id": "delsey-chatelet-air-2-0-m",
  "brand": "DELSEY PARIS",
  "model": "CHATELET AIR 2.0",
  "variant": "M 66cm / 4 DOUBLE WHEELS TROLLEY CASE（有効容量69L）",
  "url": "https://delsey.jp/products/d001676810-chatelet-air-2-0-m-66cm",
  "image": "https://delsey.jp/cdn/shop/products/delsey-chatelet-air-2.0-00167681015-01.jpg?v=1775547420",
  "price": 77000,
  "currency": "JPY",
  "price_note": "税込・通常価格（デルセー公式JP）",
  "capacity": 69,
  "capacity_exp": null,
  "weight": 4.13,
  "size": "66.5×45×28.5",
  "open": "ジッパー両開き",
  "stopper": false,
  "expandable": false,
  "wheels": "デュアルデンシティ ダブルホイール",
  "warranty": "10年",
  "colors": 4,
  "made_in": null,
  "notes": "公式表記は「外寸容量 約85L／有効容量（内寸）約69L」。特許 zipsecuritech ZST2（こじ開け対策ジップ）。ストッパー・生産国の記載なし。カラー ANGORA／BROWN／ROSE／NAVY BLUE（NAVYは在庫切れ）。",
  "pick": 5,
  "rate": {
   "light": 3,
   "func": 3,
   "design": 5,
   "trust": 3,
   "value": 3
  },
  "comment": "パリ発のクラシックなトランク風。<b>こじ開けに強いSECURITECHジッパー</b>、10年保証。アンゴラ・ブラウン・ローズと妻の黒に並べて絵になる色が揃う。ストッパーなし。",
  "fit": "クラシックな見た目が好き。妻の黒と並べて絵になる色がほしい"
 },
 {
  "id": "samsonite-c-lite-spinner69",
  "brand": "Samsonite",
  "model": "C-LITE（シーライト）",
  "variant": "スピナー69 / 68L（ブラック 122860-1041）",
  "url": "https://www.samsonite.co.jp/samsonite/c-lite/spinner69/black/ss-122860-1041.html",
  "image": "https://www.samsonite.co.jp/dw/image/v2/AAWQ_PRD/on/demandware.static/-/Sites-Samsonite/default/dwf89521a1/images/c-lite-spinner/hi-res/122860_1041_hi-res_FRONT34_1.jpg",
  "price": 89100,
  "currency": "JPY",
  "price_note": "税込・通常価格（サムソナイト公式JP）",
  "capacity": 68,
  "capacity_exp": null,
  "weight": 2.5,
  "size": "69×46×29",
  "open": "ジッパー両開き",
  "stopper": false,
  "expandable": false,
  "wheels": "ダブルホイール",
  "warranty": "条件付10年（グローバルワランティ）",
  "colors": 6,
  "made_in": "ヨーロッパ（Made in Europe）",
  "notes": "Curv®素材で2.5kgの超軽量。Recyclex™裏地（再生PET）。ブレーキ（ストッパー）の記載なし。公式サイトはCloudflare保護のためpython直取得不可、WebFetch経由で取得。画像URLはブラウザ表示可（python直取得はHTMLを返す）。",
  "pick": 6,
  "rate": {
   "light": 5,
   "func": 3,
   "design": 3,
   "trust": 4,
   "value": 2
  },
  "comment": "Curv素材で<b>68Lなのに2.5kg</b>。本体が軽い分だけ23kgの中身に使える。欧州製・10年保証。価格は高め、ストッパーなし。",
  "fit": "受託23kgをフルに使いたい。軽さに投資できる"
 },
 {
  "id": "muji-hard-carry-75",
  "brand": "無印良品",
  "model": "バーを自由に調節できる ハードキャリーケース（2026年4月リニューアル版）",
  "variant": "75L / 商品番号 23183963（オレンジ）",
  "url": "https://www.muji.com/jp/ja/store/cmdty/detail/4550723183963",
  "image": "https://www.muji.com/public/media/img/item/4550723183963_org.jpg",
  "price": 31900,
  "currency": "JPY",
  "price_note": "税込・通常価格（無印良品ネットストア）",
  "capacity": 75,
  "capacity_exp": null,
  "weight": 4.6,
  "size": "71.5×46×26",
  "open": "ジッパー両開き",
  "stopper": true,
  "expandable": false,
  "wheels": "静音設計キャスター（ストッパー機能付）",
  "warranty": null,
  "colors": 7,
  "made_in": null,
  "notes": "指示の63Lは2026年4月のリニューアルで廃止され（旧63LページはJAN 4550344913475／4550182869385とも「該当する商品がありません」）、現行ラインナップは20/36/75/105L。最も近い75Lを採用。キャリーバー高さ69.5〜105cmを1cm刻みで無段階調整、耐荷重約16kg。本体ポリカーボネート、裏地は再生ポリエステル100%。カラーは商品ページのスワッチで7色確認（グレー／オレンジ／スモーキーグリーン／ネイビー／ボルドー／スモーキーブラウン／グレージュ。報道では9色）。原産国はページ項目にあるが値を取得できず null。無印サイトは混雑ページを返すことがあり、取得はブラウザ経由。",
  "pick": 7,
  "rate": {
   "light": 2,
   "func": 4,
   "design": 3,
   "trust": 3,
   "value": 4
  },
  "comment": "2026年4月刷新で63Lが消え、75Lに。ハンドル無段階調節とストッパー、鍵不要のTSロック。<b>渋谷で現物を見て当日持ち帰れる</b>。4.6kgと重めで、旅程の7日間には少し大きい。",
  "fit": "無難で実用的なものを最短で手に入れたい"
 },
 {
  "id": "zero-halliburton-zrp-zx-check-in-s",
  "brand": "ZERO HALLIBURTON",
  "model": "ZRP-ZX（Value Edition）",
  "variant": "Check-In-S 53L / 80532",
  "url": "https://zerohalliburton.jp/products/value-edition-zrp-zx-check-in-s-53l-81532",
  "image": "https://zerohalliburton.jp/cdn/shop/files/80532_3.jpg?v=1713257547",
  "price": 66000,
  "currency": "JPY",
  "price_note": "通常価格 税込66,000円。公式でセール価格 ¥46,200（¥19,800 OFF）、セール品のため返品交換不可",
  "capacity": 53,
  "capacity_exp": null,
  "weight": 3.6,
  "size": "62×43×25",
  "open": "ジッパー両開き",
  "stopper": false,
  "expandable": false,
  "wheels": "双輪キャスター",
  "warranty": null,
  "colors": 4,
  "made_in": null,
  "notes": "ダブルリブ・鏡面PCボディ。サイズ展開はCarry-On 32L／Check-In-S 53L／Check-In-M 80L／Check-In-L 90Lだが、公式JPサイトの商品ページが確認できたのはS 53LとL 90Lのみ（M 80Lのページは見つからず）。保証はフッターに「包括的な商品保証」とあるが期間は商品ページに記載なし。ストッパー・生産国の記載なし。",
  "pick": 8,
  "rate": {
   "light": 4,
   "func": 3,
   "design": 4,
   "trust": 4,
   "value": 3
  },
  "comment": "米国老舗のダブルリブ意匠。<b>リモワより控えめで傷も目立ちにくい</b>ポリカ製。53Lと小ぶりだが3.6kgと軽く、今はセールで¥46,200。",
  "fit": "所有感がほしいが、リモワほど主張したくない。荷物は少なめ"
 },
 {
  "id": "hideo-wakamatsu-estop",
  "brand": "HIDEO WAKAMATSU",
  "model": "エストップ",
  "variant": "85-76680 / 60L（拡張時71L）",
  "url": "https://store.shopping.yahoo.co.jp/kyowa-bag/85-76680.html",
  "image": "https://item-shopping.c.yimg.jp/i/n/kyowa-bag_85-76680_i_20240527105618",
  "price": 35200,
  "currency": "JPY",
  "price_note": "メーカー希望小売価格 税込35,200円。協和公式Yahoo!店で30%OFF ¥24,640（マットブラックは在庫なし、マットホワイト残りわずか）",
  "capacity": 60,
  "capacity_exp": 71,
  "weight": 4.5,
  "size": "63×44×28（拡張時 奥行33）／本体 57×42×28",
  "open": "トップオープン（上部ポケット）＋ジッパー両開き",
  "stopper": true,
  "expandable": true,
  "wheels": "静音双輪キャスター 50mm（日乃本錠前 Lisof）",
  "warranty": "1年",
  "colors": 2,
  "made_in": "中国",
  "notes": "hideowakamatsu.com は米国向けサイト（USD表示）で日本仕様の中型は掲載なし。日本の公式は協和（kyowa-bag.co.jp）で、商品仕様は協和の直販Yahoo!店ページから取得。ワンタッチ後輪ストッパー、5cm拡張、多段階ハンドル（80〜100cm）。ABS+PCシェル。フライIIはソフトケース（M 48.5L）のため対象外。",
  "pick": 9,
  "rate": {
   "light": 3,
   "func": 4,
   "design": 4,
   "trust": 3,
   "value": 4
  },
  "comment": "日本のデザイナーブランド（協和）。<b>ストッパー・拡張・多段階ハンドルが揃って実売2.5万円前後</b>。色は2色と少なく、人と被りにくい。",
  "fit": "人と被らない日本ブランドで、機能はひと通りほしい"
 },
 {
  "id": "july-checked",
  "brand": "July",
  "model": "Checked",
  "variant": "Checked 80L（標準／CaseSafe™なし）",
  "url": "https://july.com/au/luggage/checked/",
  "image": "https://images.july-cdn.com/cdn-cgi/image/width=1200,format=auto,quality=70,fit=scale-down/https://july-cms-images.s3.ap-southeast-2.amazonaws.com/CHK_Moss_1_827bc83125.png",
  "price": 395,
  "currency": "AUD",
  "price_note": "AUD 395（豪州公式・GST込み表示）。CaseSafe™トラッカー内蔵版は AUD 445。日本円表記なし（通貨AUD）。参考: 豪州内送料無料・100日返品",
  "capacity": 80,
  "capacity_exp": null,
  "weight": 3.8,
  "size": "66×47×29（内寸 61×45×28）",
  "open": "ジッパー両開き",
  "stopper": false,
  "expandable": false,
  "wheels": "SilentMove™ 360°スピナーホイール（生涯保証）",
  "warranty": "生涯保証（製造上の欠陥）",
  "colors": null,
  "made_in": null,
  "notes": "Julyの中型はCheckedのみ（Carry On 42L／Checked 80L／Checked Plus 110L）で、目標65–70Lより大きい80L。ドイツ製ポリカーボネートシェル、陽極酸化アルミのコーナーバンパー、YKKジッパー、Y-Strap圧縮システム、20段階ハンドル。ストッパー記載なし。カラー数はページDOMから確定できず（CDNの商品画像名からは16色前後）。",
  "pick": 10,
  "rate": {
   "light": 4,
   "func": 3,
   "design": 4,
   "trust": 3,
   "value": 3
  },
  "comment": "<b>オーストラリア発</b>。シドニーに直営店があり、現地で買って土産ごと詰めて帰る案が成立する。80Lで3.8kg、生涯保証。日本でのサポートはない。",
  "fit": "現地で買う体験ごと楽しみたい。帰りの荷物が増える前提"
 },
 {
  "id": "rimowa-essential-check-in-m",
  "brand": "RIMOWA",
  "model": "Essential",
  "variant": "チェックイン M / 60L（品番 83263631 マットブラック）",
  "url": "https://www.rimowa.com/jp/ja/luggage-collection-essential-check-in-m/83263631.html",
  "image": "https://www.rimowa.com/on/demandware.static/-/Sites-rimowa-master-catalog-final/default/dw1217500b/images/large/83263631_1.png",
  "price": 179300,
  "currency": "JPY",
  "price_note": "税込・通常価格（RIMOWA公式JP）",
  "capacity": 60,
  "capacity_exp": null,
  "weight": 4.1,
  "size": "67×43×24",
  "open": "ジッパー両開き",
  "stopper": false,
  "expandable": false,
  "wheels": "RIMOWA マルチホイール®システム（ボールベアリング・ダブルホイール）",
  "warranty": "生涯保証（要オンライン登録）",
  "colors": 4,
  "made_in": null,
  "notes": "指示にあったURL（83263661）はリダイレクトされ現存せず、現行品番 83263631 で確認。カラーはページのスワッチで4色（マットブラック／グロス オレンジ／グロスグリーン／グロス スレート グレー）。「ドイツでデザイン」表記のみで生産国は記載なし。画像URLはブラウザでは表示可だが、python直接取得は403（ボット対策）。",
  "pick": 11,
  "rate": {
   "light": 4,
   "func": 3,
   "design": 5,
   "trust": 4,
   "value": 1
  },
  "comment": "所有感の頂点。Essentialはポリカで4.1kg、生涯保証。<b>傷を味と思える人向け</b>で、そうでなければストレスになる。",
  "fit": "一生ものを買う覚悟がある。傷は気にしない"
 }
];
